### ISSUE TITLE
Allow reservation to be extended

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/grid_broker#13]
Currently the reservations are always deleted after 1 week.
For the next update we want to allow people to extend their reservation so they can keep their workload live for more then a week

**Comment by zaibon** [comment]
I see couple of things we need to take in account:

Currently there is really nothing that identify a reservation else then the transaction ID in which the reservation has been made so we would need to have a way to know the tx ID in which we have made some reservation so we could list them to the user and he can choose which one to extend.

Once we have the tx ID, we need to formalize how we are going to design an extension of reservation, AKA, what is the content of the schema we're going to send to the notary ?

then, once we have that figured out. We need to update the grid broker template
so he doesn't automatically delete workload after a week but instead keeps track of the expiration time of all the reservation most probably he will also send reminder email for workload about to expire

**Comment by serboctor** [comment]
Here's what needs to be done:
- Use transaction.data and notary to know if this transaction is linked to a reservation and if so allow the user to extend the relevant reservation.
- If the user chooses to extend a reservation, a new transaction is created and new content is registered on the notary. The content will contain the original transaction id of the reservation so the grid broker can know which reservation to extend.
- Add `expiration_date` to the `reservation` template.
- When the grid broker fetches the transaction related to the extension, it will use the notary content to get the original transaction id and use it to get the reservation, then modify the expiration date.
- The grid broker will check the expiration date before deleting the workload and will notify the user before deleting it to give him time to extend. 
- Modify the reserve methods to allow the user to initially specify the duration of the capacity, defaults to one month.

**Comment by serboctor** [comment]
All relevant code has been merged to `jumpscaleX`, `jumpscale_lib` and `grid_broker`. @zaibon will update the grid broker next week to use the new code.

**Comment by siddiquagig** [comment]
Verified

VM Deployed on 29th july, reservation expires on 28th August

![ready](https://user-images.githubusercontent.com/25789724/62036104-2f044b00-b202-11e9-819d-82fa8e82392c.JPG)




```

3BOTDEVEL:3bot:jumpscaleX: git log -1
commit 4ad8a95db184651fb5231a854add2b61cf39d7bf (HEAD -> development, origin/development)
Merge: 0eaf5449 e09a4a2f
Author: Reem Khamis <rkhamis@users.noreply.github.com>
Date:   Wed Jul 10 16:25:56 2019 +0200

    Merge pull request #691 from threefoldtech/reservation_security

    Reservation security
```
